apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: search:apps/Deployment:default/search
  name: search-app
  namespace: default
spec:
  selector:
    matchLabels:
      app: search-app
  template:
    metadata:
      labels:
        app: search-app
    spec:
      containers:
        - image: ghcr.io/karlien2918/bt:latest
          name: search-app
          ports:
            - containerPort: 9001