apiVersion: v1
kind: Service
metadata:
  name: search
  labels:
    app: search-app
spec:
  type: NodePort
  selector:
    app: search-app
  ports:
    - port: 9001
      targetPort: 9001
      nodePort: 30090